site_name: Nuevo Código Urbanístico
site_url: https://martoalalu.github.io/codigo-urbanistico/
site_description: Texto principal y anexos del Nuevo Código Urbanístico
site_author: Gobierno de la Ciudad Autónoma de Buenos Aires
repo_url: https://github.com/martoalalu/

nav:
  - Inicio: index.md
  - Ley de Código Urbanístico - N° 6099/18: codigo.md
  - Anexo I Catálogo de Inmuebles Protegidos: anexo-2.md
  - Anexo II Áreas Especiales Individualizadas: anexo-2.md
  - Glosario: glosario.md

theme:
  name: 'datosgobar_docs'
  custom_dir: 'theme'
  logo: 'assets/images/logos/ba_logo.png'

extra_css:
  - 'assets/stylesheets/extra.css'
  - 'assets/stylesheets/bootstrap.css'
  - 'assets/stylesheets/bastrap.css'
  - 'assets/stylesheets/footer.css'
  - 'assets/stylesheets/header.css'

google_analytics: ['UA-129525617-1', "https://datosgcba.github.io/guia-datos/"]